// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: product.sql

package productdb

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createProduct = `-- name: CreateProduct :one
INSERT INTO product (name, description, price, stock, image_url)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, name, description, price, stock, image_url
`

type CreateProductParams struct {
	Name        string
	Description sql.NullString
	Price       int64
	Stock       sql.NullInt32
	ImageUrl    sql.NullString
}

type CreateProductRow struct {
	ID          uuid.UUID
	Name        string
	Description sql.NullString
	Price       int64
	Stock       sql.NullInt32
	ImageUrl    sql.NullString
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (CreateProductRow, error) {
	row := q.db.QueryRowContext(ctx, createProduct,
		arg.Name,
		arg.Description,
		arg.Price,
		arg.Stock,
		arg.ImageUrl,
	)
	var i CreateProductRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Price,
		&i.Stock,
		&i.ImageUrl,
	)
	return i, err
}

const getProductByID = `-- name: GetProductByID :one
SELECT id, name, description, price, stock, image_url
FROM product
WHERE id = $1 AND is_deleted = false
`

type GetProductByIDRow struct {
	ID          uuid.UUID
	Name        string
	Description sql.NullString
	Price       int64
	Stock       sql.NullInt32
	ImageUrl    sql.NullString
}

func (q *Queries) GetProductByID(ctx context.Context, id uuid.UUID) (GetProductByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getProductByID, id)
	var i GetProductByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Price,
		&i.Stock,
		&i.ImageUrl,
	)
	return i, err
}

const getProducts = `-- name: GetProducts :many
SELECT id, name, description, price, stock, image_url
FROM product
WHERE is_deleted = false
`

type GetProductsRow struct {
	ID          uuid.UUID
	Name        string
	Description sql.NullString
	Price       int64
	Stock       sql.NullInt32
	ImageUrl    sql.NullString
}

func (q *Queries) GetProducts(ctx context.Context) ([]GetProductsRow, error) {
	rows, err := q.db.QueryContext(ctx, getProducts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetProductsRow
	for rows.Next() {
		var i GetProductsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Price,
			&i.Stock,
			&i.ImageUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
