// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package product

import (
	"database/sql"

	"github.com/google/uuid"
)

type Product struct {
	ID          uuid.UUID
	Name        string
	Description sql.NullString
	Price       int64
	Stock       sql.NullInt32
	ImageUrl    sql.NullString
	IsDeleted   sql.NullBool
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
}
