// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: product.sql

package product

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const getProducts = `-- name: GetProducts :many
SELECT id, name, description, price, stock, image_url
FROM product
WHERE is_deleted = false
`

type GetProductsRow struct {
	ID          uuid.UUID
	Name        string
	Description sql.NullString
	Price       int64
	Stock       sql.NullInt32
	ImageUrl    sql.NullString
}

func (q *Queries) GetProducts(ctx context.Context) ([]GetProductsRow, error) {
	rows, err := q.db.QueryContext(ctx, getProducts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetProductsRow
	for rows.Next() {
		var i GetProductsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Price,
			&i.Stock,
			&i.ImageUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
